<?php

declare(strict_types=1);

namespace Thehouseofel\Dbsync\Domain\Support\Drivers;

use Composer\InstalledVersions;

class OracleDriver extends BaseDriver
{
    protected array $hasTextColumns = [];

    protected function validateVersion(): void
    {
        if (! InstalledVersions::isInstalled('yajra/laravel-oci8')) {
            throw new \RuntimeException("The package 'yajra/laravel-oci8' is not installed. Please install it to use the Oracle driver.");
        }

        if (version_compare(InstalledVersions::getVersion('yajra/laravel-oci8'), '12.10', '<')) {
            throw new \RuntimeException("The installed version of 'yajra/laravel-oci8' is too old. Please update to version 12.10 or higher.");
        }

        if (! ($this->connection instanceof \Yajra\Oci8\Oci8Connection)) {
            throw new \RuntimeException("The connection is not an instance of \Yajra\Oci8\Oci8Connection. Please check your Oracle connection configuration.");
        }

        $minVersion = '12c';
        if ($this->connection->isVersionBelow($minVersion)) {
            throw new \RuntimeException("Server version {$this->connection->serverVersion()} is not supported. At least version $minVersion is required.");
        }
    }

    protected function getDictionaryTableName(string $table): string
    {
        return strtoupper(parent::getDictionaryTableName($table));
    }

    public function forceDrop(string $table): void
    {
        // CASCADE CONSTRAINTS elimina las FKs que apuntan a esta tabla
        $this->connection->statement("DROP TABLE {$this->wrapTable($table)} CASCADE CONSTRAINTS PURGE");
    }

    public function truncate(string $table, string $column = 'id'): void
    {
        $wrappedTable  = $this->wrapTable($table);
        $wrappedColumn = $this->wrapColumn($column);

        $this->connection->table($table)->truncate();

        $generationType = $this->identityGenerationType($table, $column);

        if ($generationType !== null) {
            $identityClause = $this->buildIdentityClause($generationType, 'START WITH 1');
            $this->connection->statement("ALTER TABLE $wrappedTable MODIFY ($wrappedColumn $identityClause)");
        }
    }

    public function syncIdentity(string $table, string $column = 'id'): void
    {
        $wrappedTable  = $this->wrapTable($table);
        $wrappedColumn = $this->wrapColumn($column);
        $generationType = $this->identityGenerationType($table, $column);

        if ($generationType !== null) {
            $identityClause = $this->buildIdentityClause($generationType, 'START WITH LIMIT VALUE');

            $this->connection->statement(
                "ALTER TABLE $wrappedTable MODIFY ($wrappedColumn $identityClause);"
            );
        }
    }

    protected function identityGenerationType(string $table, string $column): ?string
    {
        $row = $this->connection->selectOne(
            'SELECT generation_type as mode FROM user_tab_identity_cols WHERE table_name = ? AND column_name = ?',
            [strtoupper($table), strtoupper($column)]
        );

        return isset($row->mode) ? strtoupper((string) $row->mode) : null;
    }

    protected function buildIdentityClause(string $generationType, string $startWith): string
    {
        return match ($generationType) {
            'ALWAYS' => "GENERATED ALWAYS AS IDENTITY ($startWith)",
            'BY DEFAULT' => "GENERATED BY DEFAULT AS IDENTITY ($startWith)",
            'BY DEFAULT ON NULL' => "GENERATED BY DEFAULT ON NULL AS IDENTITY ($startWith)",
            default => throw new \RuntimeException("Unsupported Oracle identity generation type: $generationType"),
        };
    }
}
