<?php

declare(strict_types=1);

namespace Thehouseofel\Dbsync\Domain\Support\Drivers;

use Composer\InstalledVersions;
use Thehouseofel\Dbsync\Infrastructure\Models\DbsyncTable;

class OracleDriver extends BaseDriver
{
    protected array $hasTextColumns = [];

    protected function validateVersion(): void
    {
        if (! InstalledVersions::isInstalled('yajra/laravel-oci8')) {
            throw new \RuntimeException("The package 'yajra/laravel-oci8' is not installed. Please install it to use the Oracle driver.");
        }

        if (version_compare(InstalledVersions::getVersion('yajra/laravel-oci8'), '12.10', '<')) {
            throw new \RuntimeException("The installed version of 'yajra/laravel-oci8' is too old. Please update to version 12.10 or higher.");
        }

        if (! ($this->connection instanceof \Yajra\Oci8\Oci8Connection)) {
            throw new \RuntimeException("The connection is not an instance of \Yajra\Oci8\Oci8Connection. Please check your Oracle connection configuration.");
        }

        $minVersion = '12c';
        if ($this->connection->isVersionBelow($minVersion)) {
            throw new \RuntimeException("Server version {$this->connection->serverVersion()} is not supported. At least version $minVersion is required.");
        }
    }

    protected function getDictionaryTableName(string $table): string
    {
        return strtoupper(parent::getDictionaryTableName($table));
    }

    public function forceDrop(string $table): void
    {
        // CASCADE CONSTRAINTS elimina las FKs que apuntan a esta tabla
        $this->connection->statement("DROP TABLE {$this->wrapTable($table)} CASCADE CONSTRAINTS PURGE");
    }

    public function truncate(string $table, string $column = 'id'): void
    {
        $upperColumn = strtoupper($column);

        $this->connection->table($table)->truncate();

        $this->connection->statement("ALTER TABLE {$this->wrapTable($table)} MODIFY ($upperColumn GENERATED AS IDENTITY (START WITH 1))");
    }

    public function syncIdentity(string $table, string $column = 'id'): void
    {
        $wrappedTable = $this->wrapTable($table);
        $wrappedColumn = $this->wrapColumn($column);

        $this->connection->statement(
            "ALTER TABLE $wrappedTable MODIFY ($wrappedColumn GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));"
        );
    }

    public function insertAuto(DbsyncTable $table, string $targetTable, array $rows): void
    {
        if ($table->insert_row_by_row && $this->hasTextLikeColumns($table)) {
            $this->insertRowByRow($targetTable, $rows);
            return;
        }

        $this->insertBulk($targetTable, $rows);
    }

    protected function hasTextLikeColumns(DbsyncTable $table): bool
    {
        $tableKey = $table->id;

        return $this->hasTextColumns[$tableKey] ??= $table->columns->contains(function ($column) {
            return in_array($column->method, ['text', 'mediumText', 'longText']);
        });
    }
}
